# spring.profiles.default=dev

spring.config.import=optional:file:./application-private.properties,optional:file:/config/application-private.properties


# application.properties 혹은 환경변수
llm.recommender.connect-timeout-ms=10000
llm.recommender.read-timeout-ms=120000
llm.recommender.max-in-mem-bytes=33554432


# 개발용: 오류 응답에 메시지/스택 표시
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# 웹/디스패처/직렬화 로그 강화
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG


